name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      ########################################
      # Checkout Repository
      ########################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ########################################
      # Setup Terraform
      ########################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      ########################################
      # Terraform Format Check
      ########################################

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      ########################################
      # Terraform Init
      # Backend disabled because the S3
      # backend bucket is not created yet.
      ########################################

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: environments/dev

      ########################################
      # Terraform Validate
      ########################################

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      ########################################
      # Setup TFLint
      ########################################

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      ########################################
      # Initialize TFLint Plugins
      ########################################

      - name: TFLint Init
        run: tflint --init

      ########################################
      # Run TFLint
      ########################################

      - name: Run TFLint
        run: tflint --recursive

      ########################################
      # Setup Python
      ########################################

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      ########################################
      # Install Checkov
      ########################################

      - name: Install Checkov
        run: pip install checkov

      ########################################
      # Run Checkov
      ########################################

      - name: Run Checkov
        run: checkov -d . --framework terraform